[build]
functions = "./functions"
[context.production.environment]
    REACT_APP_AUTH_DOMAIN = 'dev-62cb2kv7oo3jca36.us.auth0.com'
    REACT_APP_AUTH_CLIENT_ID = 'aoe1QZgHq2hqs0lcLcrIXCQSRTfskmtu'
    REACT_APP_STRIPE_PUBLIC_KEY = 'pk_test_51NBYyJAdzgSlsFiK8YTjJgYj2hrGd0iu3CnqWyA3AIfB7EFFqTmI6GwrYoanpC4KbMhoVscGABFwttAMRGV9KDey00TmjOstnf'
    REACT_APP_STRIPE_SECRET_KEY = 'sk_test_51NBYyJAdzgSlsFiKMgGbPVhGeos7CkyabSqGqX92uJcHxAuaQPd1d6CiiUup6knu2GZOSnv4j0denNLrgakWUqTj00orwZajet'